version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mysql_db
    build: . # docker build . -t img-name
    container_name: cons-node
    env_file: .env
    environment:
      - DB_HOST=mysql_db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_DIALECT=$DB_DIALECT
      - DB_PORT=$DB_PORT
    ports:
      - 3500:8080
    networks:
      - node-network
volumes:
  mysql_db:
    driver: local
networks:
  node-network: